config/routes.rb
Rails.application.routes.draw do
 
  

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  resources :users
    root 'users#index'

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
     belongs_to :user
      default_scope -> { order(created_at: :desc) }
     validates :user_id, presence: true
    validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
     has_many :microposts, dependent: :destroy
     validates :name, length: { maximum: 140 },
     presence: true
      validates:email,length: { maximum:140},
      presence: true
       validates:lop,length: { maximum:140},
      presence: true
       validates:so,length: { maximum:140},
      presence: true
       
   def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("name LIKE ?", "%#{search}%")
   


 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
  @users = User.all
 if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  
end

  
 

  # GET /users/1
  # GET /users/1.json
  def show
      @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Đã tạo hồ sơ.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Cập Nhật Hồ Sơ Thành Công!!.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Hồ Sơ đã được xóa.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet,                                    only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :lop, :so, :timestamps)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def log_in(user)
    session[:user_id] = user.id
  end
   def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= yield(:title) %> Quản Lý Sinh Viên</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

 
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!--<%= link_to "Home", root_path, id: "logo" %>-->
   
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>
  
</div>
</header>
</body>
</html>

app/views/layouts/header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>
<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1 style="text-align:center">About</h1>
<p>
  It <a href="http://www.railstutorial.org/">help user can see all student in a website
</a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://https://www.facebook.com/profile.php?id=100011442782742">QLSV</a>.
  This is the website off Tech Ninjas.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<p style="center,font-size:300%" >Nếu bạn cần trợ giúp hãy liên hệ cho chúng tôi theo sđt:</p>
<h1 style="text-align:center;">0984571413-Mr.T</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>


<p>
                    <button type="button" class="btn btn-default btn-lg"> <b>This is the home page for the</b>
  
 
                   <a href="https://kol-thanguet.c9users.io/">Students of UET</a>
                  <b> sample application.</b></button>
  
</p>

             <div><%= link_to image_tag("2e5ef6cc0f51.png", alt: "UET logo"),
            'https://kol-thanguet.c9users.io/' %></div>
            
 
   

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name,"Tên" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email,"Quê Quán" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :lop,"Lớp Học" %><br>
    <%= f.text_field :lop %>
  </div>
 <div class="field">
    <%= f.label :so,"Điểm TB" %><br>
    <%= f.text_field :so %>
  </div>
   

  <div class="actions">
    <%= f.submit "Tạo Hồ Sơ" %>
  
</div>
     
<% end %>

app/views/users/edit.html.erb
<h1 class="bg-primary">Chỉnh Sửa Hồ Sơ</h1>

<%= render 'form' %>


<button type="button" class="btn btn-info"><%= link_to 'Show', @user %> </button>
<button type="button" class="btn btn-primary"><%= link_to 'Back', users_path %></button>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Quản lý hồ sơ sinh viên</h1>
<%= form_tag(users_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
  <%= submit_tag "Search" %>
<% end %>

<table class="table table-hover"">
  <thead>
    <tr>
      <th>Tên</th>
      <th>Quê Quán</th>
      <th>Hiển Thị</th>
      <th>Chỉnh Sửa</th>
      <th>Xóa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name   %></td>
        <td><%= user.email %></td>
  
        <td><%= link_to ' Show ', user %></td>
        <td><%= link_to ' Edit ', edit_user_path(user) %></td>
        <td><%= link_to ' Delete ', user, method: :delete, data: { confirm: 'Are you want to delete ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-success"><strong><%= link_to 'Tạo hồ sơ mới', new_user_path %></strong></button>


 

app/views/users/new.html.erb
<h1>Tạo Hồ Sơ Mới</h1>

<%= render 'form' %>


<button type="button" class="btn btn-primary"><%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Tên</th>
      <th>Quê Quán</th>
      <th>Lớp Học</th>
      <th>Điểm TB</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @user.name %></td>
      <td> <a href="https://www.google.com/maps" target="blank"><%= @user.email %>
  </a></td>
  <td><%= @user.lop %></td>
  <td> <%= @user.so %>
   <a href="http://daotao.vnu.edu.vn/dkmh/login.asp" target="blank"> Xem</a></td>
  
    </tr>
  </tbody>
</table>
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>


<button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_user_path(@user) %> </button>

<button type="button" class="btn btn-primary"><%= link_to 'Back', users_path %></button>